### PR TITLE
Move GetOptimalPolicy for the game of Kuhn Poker to kuhn_poker namesp…

### PR DESCRIPTION
**Pull request by michalsustr**
Move GetOptimalPolicy for the game of Kuhn Poker to kuhn_poker namespace. Expose the same function via pybind.

The file `open_spiel/python/games/data.py` can be also deleted, along with its test (which can be moved to c++ side). I can do this in a subsequent PR.

### CODE REVIEW

**Comment by michalsustr** [comment]
Not sure why the job `build_and_test / build (ubuntu-20.04, 3.8, 1, OFF, OFF, OFF) (pull_request)` failed... it complains the file `pybind11/games_kuhn_poker.cc` is missing, but it's in the repo, and other tests that build pyspiel worked... Maybe the test is acting up?

**Comment by lanctot** [comment]
Restarted the test.

**Comment by michalsustr** [comment]
Hmm weird, indeed it was missing! I definitely implemented it... but maybe forgot to add it... -- Update: I think it might be because 
`pybind11/` is in .gitignore and somehow it also matched this directory (though I guess it should only match the top-level pybind/) so I didn't add those files.

**Comment by lanctot** [comment]
Very nice change, thanks for doing this!

**Pull request merged**
