### PR TITLE
ConvNet DQN example for ConnectFour

### PR DESCRIPTION
**Pull request by jamesdfrost**
I've implemented a simple ConvNet example which is based on the DQN Algorithm. 

The algorithm is called DQN_Conv.py and has the following differences from the fully connected example:

instead of taking just one array of hidden_layers_sizes it takes the following:
- convolutional_layers_sizes      (e.g. [64,32] )
- kernel_shape                           (e.g. [3,3] )
- fully_connected_layers_sizes   (e.g. [64,16] )

it also takes the state_representation_shape instead of the state_representation_size to ensure the inputs are formatted correctly. (this necessitated a change to rl_environment to return this.

At the moment I've stuck with Sonnet for defining the network, but that seems to have a limitation in the construction of convolutional layers, which must number 2 currently. Will look at this in a future revision.

Have implemented both a feedforward and convolutional version of connect_four so the two networks can be compared. To run, type:

```bash
python3 open_spiel/python/examples/connect_four_dqn_conv.py
python3 open_spiel/python/examples/connect_four_dqn.py
```

### CODE REVIEW

**Comment by lanctot** [comment]
Great!! We will take a look.

**Comment by jamesdfrost** [comment]
Have added a test to this as well now, dqn_conv_test.py, but not sure how to get this added to the master tests list.

**Comment by lanctot** [comment]
Hi @jamesdfrost , if I understand correctly, you have a completely separate DQN implementation for convolutional networks (`dqn_conv.py`).

Is there a reason to prefer this over just supporting conv nets in the original DQN code? The code should not be _that_ different, right... just how the network is invoked?

**Comment by lanctot** [comment]
Likewise, couldn't we also merge connect_four_dqn.py and connect_four_dqn_conv.py?

**Comment by jamesdfrost** [comment]
@lanctot - makes sense. I'll change the DQN code so you can pass it details of either a convolutional or a feed forward network. The differences are just in the network itself and also how the data is reshaped, otherwise basically identical.

**Comment by lanctot** [comment]
Great! Can I ask that you do the same for the example as well (merge `connect_four_dqn.py` and `connect_four_dqn_conv.py`)? Thanks -- I'll integrate it shortly afterward!

**Comment by jamesdfrost** [comment]
I'm going to resubmit this with the changes above over the Christmas break - have been struggling for time due to work commitments over the last month.

**Comment by lanctot** [comment]
No rush, of course! Thanks for making those changes and your continued contributions. Happy holidays@

**Pull request closed without merging**
