### PR TITLE
[Fix typo] Go is Deterministic. 

### PR DESCRIPTION
**Pull request by yukarinoki**
"Go is Non-deterministic" has been corrected to Deterministic.

See also: #374

### CODE REVIEW

**Comment by lanctot** [comment]
Thank you! It is imported, so will get merged in the next update (next year).

**Comment by yukarinoki** [comment]
I found another typo in docs/developer_guide.md, can I include it in this pull request?
If it's not good, I'd be happy to fix it on your side.

```
docs/developer_guide.md#L17
*   `open_spiel/games`: Contains the games ++ implementations.
```
This should be `C++`, not `++`.


```
docs/developer_guide.md#L27
## CPP and Python implementations.
```
It may be a matter of preference, but for consistency in notation, this might be `C++`, not `CPP`

**Comment by lanctot** [comment]
Nice catches. I already imported your other one, so please make a separate PR for this.

**Comment by yukarinoki** [comment]
@lanctot  I just created a pull request #468. 
 Thank you for taking your time to make these minor correction.

**Pull request merged**
