### PR TITLE
Universal Poker Implementation based on ACPC Server

### PR DESCRIPTION
**Pull request by dennisjay**
Dear OpenSpiel Team,

I read in this comment [https://github.com/deepmind/open_spiel/issues/5] that there is the need of a Poker Implementation that does support large poker games as well. Here it is! A full configurable poker implementation based on the ACPC Server (annual poker competition clib).

Here are some advantages of this lib:
- Fully customizable (players, deck size, boardcard count, holecard count, blinds, ...)
- ACPC Headers are fully abstracted so they do not appear in this lib header files (which otherwise could break namespaces)
- Fast (20% faster than Leduc-Poker Impl for a similar Game) 
- Support for bigger Graphs Like Teaxas Holdem unlimited

Some things that should be cared about (Just as far I know)
- Clearance of Copyright and Licence (sorry don't know much about it).
- API and C++ Docs of Methods
- more automated Tests
- Limit Games don't work right now as good
- Configurable Betting abstraction (now hardcoded to All-In, Bet-Pot, Call/Check and Fold)

Please give me some feedback about the code as I'm very interested how I did.

Best Regards
DJ

### CODE REVIEW

**Comment by dennisjay** [comment]
I added the ACPC Licence im my branch

**Comment by dennisjay** [comment]
@googlebot I signed it!

**Comment by kuzmenkoY** [comment]
@googlebot I signed it!

**Comment by lanctot** [comment]
Hi @dennisjay, wow this is incredible!

It will take us a bit of time to look at this. We have to check that licenses are compatible, then look over all the code.

In the meantime, do you know why the checks are failing (including the cla)? Travis CI also seems to show a build error.

**Comment by kuzmenkoY** [comment]
@googlebot I consent.

**Comment by dennisjay** [comment]
@lanctot CLAs are done. Some python unit test are still failing. Will look at it tonight in the evening. Perhaps I can ask somebody to write some c++ docs and automated tests if required.

**Comment by lanctot** [comment]
Hi @dennisjay , how much modification did you have to make to the actual ACPC code? If it's only small changes, then what do you think of forking ACPC adding your changes, and then just have OpenSpiel depend on it? 

This could alleviate any licensing issues because the code would not get bundled with OpenSpiel, and would be downloaded separately. It would also be slightly cleaner and less code to review :)

**Comment by dennisjay** [comment]
@lanctot Yeah we can do that I did only one modification to ACPC to solve some pointer issues when creating the game. But that can be handled another way so that we can use the original source only. Should I download it from this rep then [https://github.com/ethansbrown/acpc] or the tar.gz file from [http://www.computerpokercompetition.org/downloads/code/competition_server/project_acpc_server_v1.0.42.tar.bz2] ?

**Comment by dennisjay** [comment]
Actually found a solution for this:

1. I forked https://github.com/ethansbrown/acpc and compared it with the version provided under http://www.computerpokercompetition.org/downloads/code/competition_server/project_acpc_server_v1.0.42.tar.bz2

2. There were some small differences regarding these two versions and the one on server was newer as I suspect

3. So I commited the new version now to my fork and used this (master) in install.sh 

4. So the source is completly untouched now and i patched acpc_cpp to use the original version

**Comment by jblespiau** [comment]
Thanks for contributing. This has been integrated and will be available on the next push to Github.

I reformatted it, so that it uses the same style as the rest (https://google.github.io/styleguide/cppguide.html).
We also added an implementation for `UniversalPokerState::ActionToString`. We did not check it thoroughly though, given its size.

We made it a conditional dependency, i.e. by default it's not downloaded and linked. One need to set a global variable to ON (in scripts/global_variables.sh). However, it's tested on Travis CI.

I hope this will be useful to the community and that people will step forward to continue to improve and maintain it.

Thank you again.

**Comment by lanctot** [comment]
JB, can we leave these open until the update? They get closed automatically and linked with the commits.

**Comment by lanctot** [comment]
> JB, can we leave these open until the update? They get closed automatically and linked with the commits.

I guess it must not have auto-closed on the update because I re-opening it or because there were conflicts, so I'm closing this now. The code is in.. thanks @jblespiau !

**Comment by dennisjay** [comment]
Thanks @lanctot und @jblespiau for the review and to give me that opportunity. :-)

**Comment by lanctot** [comment]
Thank _you_ for this, it was one of our largest (if not *the* largest) PR to date and a non-trivial amount of work. Thanks for putting up with the back-and-forth. This is a really solid addition to the code and makes it possible to apply these RL algorithm to standard poker games which have been used in the literature!

**Comment by jblespiau** [comment]
@dennisjay Hi. I am trying to use the code, and I had a few questions (it may be easier by email?).

In particular, I was wondering what was wrong in:

uint32_t BettingTree::GetMaxBettingActions() const {
  return IsLimitGame() ? 3 : 4;
}

given that:

ALL_ACTIONS[5] = {ACTION_DEAL, ACTION_FOLD,
                                                ACTION_CHECK_CALL,
                                                ACTION_BET_POT, ACTION_ALL_IN};

Should we remove the ACTION_ALL_IN from there, given it will never be played?

**Pull request closed without merging**
