### PR TITLE
Use type 'Player' instead of 'int' in as many places as possible.

### PR DESCRIPTION
**Pull request by michalsustr**
Refactor based on #46 

Touches a lot of code. :-)

I found it useful to use a struct for finding out the cases:
```
struct Player {
    int id;

    inline bool operator==(const Player &rhs) const { return id == rhs; }
    inline bool operator==(const int &rhs) const { return id == rhs; }
    inline bool operator!=(const Player &rhs) const { return !(rhs == *this); }
    inline bool operator<(const Player &rhs) const { return id < rhs; }
    inline bool operator<=(const Player &rhs) const { return id <= rhs; }
    inline bool operator>=(const Player &rhs) const { return id >= rhs; }
    inline bool operator<(const int &rhs) const { return id < rhs; }
    inline bool operator<=(const int &rhs) const { return id <= rhs; }
    inline bool operator>=(const int &rhs) const { return id >= rhs; }
    inline bool operator+(const Player &rhs) const { return id + rhs; }
    inline bool operator-(const Player &rhs) const { return id - rhs; }
    inline void operator++(int) { id++; }
    inline void operator++() { id++; }
    friend std::ostream &operator<<(std::ostream &os, const Player &player) {
        os << player;
        return os;
    }
};
```
since the compiler interchanges `Player` and `int` freely ... (unlike for example in Haskell)

### CODE REVIEW

**Comment by michalsustr** [comment]
@googlebot I fixed it.

**Comment by lanctot** [comment]
Wow, this is amazing, thanks!

Just a quick heads-up: our travis testing mechanism is currently broken and we're in the process of fixing it. We will take a look once that's done (give it a day or two, though).

**Comment by lanctot** [comment]
Quick question since it is difficult to find on my phone: did you remove that custom Player struct?

I would guess not because the code shows Player rather than PlayerId. I would rather keep using the enum PlayerId since it is already an int already (and we don't need a custom type and overriding methods) and we are already using the PlayerId values in other places.

**Comment by lanctot** [comment]
No, thanks. I prefer the enum for simplicity. Kind of the same argument as the other thread. I do not like introducing custom types for things that are simple (plain old data), just makes everything unnecessarily complicated... the benefits are not worth what you pay IMO.

**Comment by michalsustr** [comment]
Unfortunately we can't have `LegalActions(PlayerId player)`, because a call `LegalActions(0)` will not compile: https://repl.it/repls/SupportiveMonstrousCoins , so there needs to be a `Player` typedef.

**Comment by lanctot** [comment]
Ok, instead of typedef, can you add `using Player = int;` here: https://github.com/deepmind/open_spiel/blob/9a0848880400eb26e481ddfdc558b1b3d075e154/open_spiel/spiel_utils.h#L85 ?

**Comment by lanctot** [comment]
Ok @michalsustr , I've started to merge this one. Should be available in our next push to github. Thanks!

**Comment by michalsustr** [comment]
Oh, ok :) I wanted to do the Player{x} -> x sometime in the evening, but that should be a quick regex search & replace. The using is there already.

**Pull request merged**
