### PR TITLE
Update cfr.py

### PR DESCRIPTION
**Pull request by eugenevinitsky**
Fix one tiny spelling mistake

### CODE REVIEW

**Comment by lanctot** [comment]
Thanks! Seems to be a problem with the CLA, which is odd.. didn't think we used that anymore.

**Comment by lanctot** [comment]
Can you follow the instructions under the Details of the CLA panel above? I'm guessing it's picking up your google email still, if you used it on your account previously.

**Comment by lanctot** [comment]
Hi @eugenevinitsky, did you want to try fixing the CLA issue?

**Comment by eugenevinitsky** [comment]
Hi @lanctot sorry about that, github often goes to spam for me! It's fixed now.

**Pull request merged**
