### PR TITLE
Add new game: Stratego/Yorktown

### PR DESCRIPTION
**Pull request by BluemlJ**
Dear OpenSpiel community,

I added a little game implementation for the board game called Stratego,  a large game with imperfect information and deterministic actions. The game implementation is called Yorktown and can play Stratego and Barrage Stratego and other game variations like Duell. In my opinion, this is a cool testbed for RL/DRL on imperfect games. 

The game was implemented by following the documentation to add new games and succeeding in all tests on my local machine.
This commits 4 new files for the game (Yorktown.cc, yorktown.h, yorktown_board.cc, yorktown_board.h) and adds the game to the CMakeList and pySpiel_test file. 

It is possible to use this implementation within RL. This was tested by myself as part of my master thesis. 

I do not have checked if there are any legal or copyright problems with Stratego.

If you have any questions, feel free to ask,
Jannis

### CODE REVIEW

**Comment by BluemlJ** [comment]
@googlebot I fixed it.

**Comment by BluemlJ** [comment]
@googlebot I fixed it.

**Comment by lanctot** [comment]
Thanks @BluemlJ. I agree Stratego is a great game for RL research. However, we cannot import  it into our repos because the game is protected under copyright.

For a previous case like this one, we were able to offer a mention on the game implementation on our games list page (but no link), if you were to host it in your own fork.

Would this interest you? If so, I will contact our legal team again to be sure.

**Comment by BluemlJ** [comment]
Hello @lanctot,
If it is impossible to integrate Stratego into OpenSpiel legally, it would be really nice to get mentioned on the games list page. 
I would host the fork. 

However, I would first try to contact Jumbo (game publisher) and ask whether it would be okay from Jumbo's side to include my implementation here if there are no problems with this from your side.

**Comment by lanctot** [comment]
Ok, great. Yes permissions have been obtained for hosting implementations of games before, e.g. for the Hanabi Learning Environment. It does take some time and the chance of getting them depend strongly on the companies and parties involved. Please let us know if you get any responses.

**Comment by rhalbersma** [comment]
There is an active Stratego community with a 25 year history of live World Championships (Demis Hassabis even played in a few!), with close contacts with the copyright holding company Jumbo (who sponsor such tournaments). I can ask around in the Dutch Stratego Association on how to approach Jumbo to green light Stratego agents.

More generally, it would be good to have some legal precedent that makes it OK to write agents for arbitrary copyrighted games, as long as one does not markets this as a separate commercial product.

**Comment by BluemlJ** [comment]
Hey @rhalbersma,
this would be great. I tried to contact Jumbo a few times in the last month, but did not get any response from them. I would be really helpful if someone knows how to get an OK from Jumbo or knows a person to contact to talk about this.

A general OK would be great especially in research, and as far as I know, in some countries there are such laws but unfortunately not in all countries (and in mine) but that's a completely different topic ^^

**Pull request closed without merging**
