### PR TITLE
Remove i386 from architecture list.

### PR DESCRIPTION
**Pull request by MaxOSmith**
Including i368 as an architecture forces `apt update` to hit multiple dead package servers. 

When building the docker container: `docker build --no-cache --target base -t openspiel -f Dockerfile.base .` The following is produced:
```
[+] Building 6.5s (7/24)
 => [internal] load build definition from Dockerfile.base                                                                                 0.0s
 => => transferring dockerfile: 1.25kB                                                                                                    0.0s
 => [internal] load .dockerignore                                                                                                         0.0s
 => => transferring context: 2B                                                                                                           0.0s
 => [internal] load metadata for docker.io/library/ubuntu:20.04                                                                           0.3s
 => CACHED [base  1/20] FROM docker.io/library/ubuntu:20.04@sha256:0e0402cd13f68137edb0266e1d2c682f217814420f2d43d300ed8f65479b14fb       0.0s
 => [internal] load build context                                                                                                         0.1s
 => => transferring context: 253.62kB                                                                                                     0.1s
 => [base  2/20] RUN apt update                                                                                                           3.4s
 => ERROR [base  3/20] RUN dpkg --add-architecture i386 && apt update                                                                     2.6s
------
 > [base  3/20] RUN dpkg --add-architecture i386 && apt update:
#6 0.200
#6 0.200 WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
#6 0.200
#6 0.448 Hit:1 http://ports.ubuntu.com/ubuntu-ports focal InRelease
#6 0.531 Hit:2 http://ports.ubuntu.com/ubuntu-ports focal-updates InRelease
#6 0.632 Hit:3 http://ports.ubuntu.com/ubuntu-ports focal-backports InRelease
#6 0.729 Hit:4 http://ports.ubuntu.com/ubuntu-ports focal-security InRelease
#6 0.923 Ign:5 http://ports.ubuntu.com/ubuntu-ports focal/multiverse i386 Packages
#6 0.923 Ign:6 http://ports.ubuntu.com/ubuntu-ports focal/universe i386 Packages
#6 0.923 Ign:7 http://ports.ubuntu.com/ubuntu-ports focal/main i386 Packages
#6 0.923 Ign:8 http://ports.ubuntu.com/ubuntu-ports focal/restricted i386 Packages
#6 0.923 Ign:9 http://ports.ubuntu.com/ubuntu-ports focal-updates/main i386 Packages
#6 0.923 Ign:10 http://ports.ubuntu.com/ubuntu-ports focal-updates/multiverse i386 Packages
#6 0.923 Ign:11 http://ports.ubuntu.com/ubuntu-ports focal-updates/restricted i386 Packages
#6 0.923 Ign:12 http://ports.ubuntu.com/ubuntu-ports focal-updates/universe i386 Packages
#6 0.923 Ign:13 http://ports.ubuntu.com/ubuntu-ports focal-backports/main i386 Packages
#6 0.924 Ign:14 http://ports.ubuntu.com/ubuntu-ports focal-backports/universe i386 Packages
#6 1.176 Ign:15 http://ports.ubuntu.com/ubuntu-ports focal-security/restricted i386 Packages
#6 1.176 Ign:16 http://ports.ubuntu.com/ubuntu-ports focal-security/universe i386 Packages
#6 1.176 Ign:17 http://ports.ubuntu.com/ubuntu-ports focal-security/multiverse i386 Packages
#6 1.176 Ign:18 http://ports.ubuntu.com/ubuntu-ports focal-security/main i386 Packages
#6 1.176 Ign:5 http://ports.ubuntu.com/ubuntu-ports focal/multiverse i386 Packages
#6 1.176 Ign:6 http://ports.ubuntu.com/ubuntu-ports focal/universe i386 Packages
#6 1.176 Ign:7 http://ports.ubuntu.com/ubuntu-ports focal/main i386 Packages
#6 1.177 Ign:8 http://ports.ubuntu.com/ubuntu-ports focal/restricted i386 Packages
#6 1.177 Ign:9 http://ports.ubuntu.com/ubuntu-ports focal-updates/main i386 Packages
#6 1.177 Ign:10 http://ports.ubuntu.com/ubuntu-ports focal-updates/multiverse i386 Packages
#6 1.280 Ign:11 http://ports.ubuntu.com/ubuntu-ports focal-updates/restricted i386 Packages
#6 1.280 Ign:12 http://ports.ubuntu.com/ubuntu-ports focal-updates/universe i386 Packages
#6 1.280 Ign:13 http://ports.ubuntu.com/ubuntu-ports focal-backports/main i386 Packages
#6 1.280 Ign:14 http://ports.ubuntu.com/ubuntu-ports focal-backports/universe i386 Packages
#6 1.280 Ign:15 http://ports.ubuntu.com/ubuntu-ports focal-security/restricted i386 Packages
#6 1.280 Ign:16 http://ports.ubuntu.com/ubuntu-ports focal-security/universe i386 Packages
#6 1.373 Ign:17 http://ports.ubuntu.com/ubuntu-ports focal-security/multiverse i386 Packages
#6 1.373 Ign:18 http://ports.ubuntu.com/ubuntu-ports focal-security/main i386 Packages
#6 1.373 Ign:5 http://ports.ubuntu.com/ubuntu-ports focal/multiverse i386 Packages
#6 1.373 Ign:6 http://ports.ubuntu.com/ubuntu-ports focal/universe i386 Packages
#6 1.383 Ign:7 http://ports.ubuntu.com/ubuntu-ports focal/main i386 Packages
#6 1.383 Ign:8 http://ports.ubuntu.com/ubuntu-ports focal/restricted i386 Packages
#6 1.383 Ign:9 http://ports.ubuntu.com/ubuntu-ports focal-updates/main i386 Packages
#6 1.383 Ign:10 http://ports.ubuntu.com/ubuntu-ports focal-updates/multiverse i386 Packages
#6 1.384 Ign:11 http://ports.ubuntu.com/ubuntu-ports focal-updates/restricted i386 Packages
#6 1.384 Ign:12 http://ports.ubuntu.com/ubuntu-ports focal-updates/universe i386 Packages
#6 1.485 Ign:13 http://ports.ubuntu.com/ubuntu-ports focal-backports/main i386 Packages
#6 1.485 Ign:14 http://ports.ubuntu.com/ubuntu-ports focal-backports/universe i386 Packages
#6 1.485 Ign:15 http://ports.ubuntu.com/ubuntu-ports focal-security/restricted i386 Packages
#6 1.485 Ign:16 http://ports.ubuntu.com/ubuntu-ports focal-security/universe i386 Packages
#6 1.575 Ign:17 http://ports.ubuntu.com/ubuntu-ports focal-security/multiverse i386 Packages
#6 1.575 Ign:18 http://ports.ubuntu.com/ubuntu-ports focal-security/main i386 Packages
#6 1.576 Ign:5 http://ports.ubuntu.com/ubuntu-ports focal/multiverse i386 Packages
#6 1.578 Ign:6 http://ports.ubuntu.com/ubuntu-ports focal/universe i386 Packages
#6 1.578 Ign:7 http://ports.ubuntu.com/ubuntu-ports focal/main i386 Packages
#6 1.578 Ign:8 http://ports.ubuntu.com/ubuntu-ports focal/restricted i386 Packages
#6 1.676 Ign:9 http://ports.ubuntu.com/ubuntu-ports focal-updates/main i386 Packages
#6 1.676 Ign:10 http://ports.ubuntu.com/ubuntu-ports focal-updates/multiverse i386 Packages
#6 1.677 Ign:11 http://ports.ubuntu.com/ubuntu-ports focal-updates/restricted i386 Packages
#6 1.677 Ign:12 http://ports.ubuntu.com/ubuntu-ports focal-updates/universe i386 Packages
#6 1.774 Ign:13 http://ports.ubuntu.com/ubuntu-ports focal-backports/main i386 Packages
#6 1.775 Ign:14 http://ports.ubuntu.com/ubuntu-ports focal-backports/universe i386 Packages
#6 1.775 Ign:15 http://ports.ubuntu.com/ubuntu-ports focal-security/restricted i386 Packages
#6 1.775 Ign:16 http://ports.ubuntu.com/ubuntu-ports focal-security/universe i386 Packages
#6 1.775 Ign:17 http://ports.ubuntu.com/ubuntu-ports focal-security/multiverse i386 Packages
#6 1.775 Ign:18 http://ports.ubuntu.com/ubuntu-ports focal-security/main i386 Packages
#6 1.869 Ign:5 http://ports.ubuntu.com/ubuntu-ports focal/multiverse i386 Packages
#6 1.869 Ign:6 http://ports.ubuntu.com/ubuntu-ports focal/universe i386 Packages
#6 1.869 Ign:7 http://ports.ubuntu.com/ubuntu-ports focal/main i386 Packages
#6 1.869 Ign:8 http://ports.ubuntu.com/ubuntu-ports focal/restricted i386 Packages
#6 1.965 Ign:9 http://ports.ubuntu.com/ubuntu-ports focal-updates/main i386 Packages
#6 1.965 Ign:10 http://ports.ubuntu.com/ubuntu-ports focal-updates/multiverse i386 Packages
#6 1.965 Ign:11 http://ports.ubuntu.com/ubuntu-ports focal-updates/restricted i386 Packages
#6 1.965 Ign:12 http://ports.ubuntu.com/ubuntu-ports focal-updates/universe i386 Packages
#6 1.965 Ign:13 http://ports.ubuntu.com/ubuntu-ports focal-backports/main i386 Packages
#6 1.965 Ign:14 http://ports.ubuntu.com/ubuntu-ports focal-backports/universe i386 Packages
#6 1.975 Ign:15 http://ports.ubuntu.com/ubuntu-ports focal-security/restricted i386 Packages
#6 1.976 Ign:16 http://ports.ubuntu.com/ubuntu-ports focal-security/universe i386 Packages
#6 1.976 Ign:17 http://ports.ubuntu.com/ubuntu-ports focal-security/multiverse i386 Packages
#6 1.976 Ign:18 http://ports.ubuntu.com/ubuntu-ports focal-security/main i386 Packages
#6 2.077 Err:5 http://ports.ubuntu.com/ubuntu-ports focal/multiverse i386 Packages
#6 2.077   404  Not Found [IP: 185.125.190.36 80]
#6 2.079 Ign:6 http://ports.ubuntu.com/ubuntu-ports focal/universe i386 Packages
#6 2.079 Ign:7 http://ports.ubuntu.com/ubuntu-ports focal/main i386 Packages
#6 2.079 Ign:8 http://ports.ubuntu.com/ubuntu-ports focal/restricted i386 Packages
#6 2.079 Err:9 http://ports.ubuntu.com/ubuntu-ports focal-updates/main i386 Packages
#6 2.081   404  Not Found [IP: 185.125.190.36 80]
#6 2.081 Ign:10 http://ports.ubuntu.com/ubuntu-ports focal-updates/multiverse i386 Packages
#6 2.081 Ign:11 http://ports.ubuntu.com/ubuntu-ports focal-updates/restricted i386 Packages
#6 2.083 Ign:12 http://ports.ubuntu.com/ubuntu-ports focal-updates/universe i386 Packages
#6 2.083 Err:13 http://ports.ubuntu.com/ubuntu-ports focal-backports/main i386 Packages
#6 2.083   404  Not Found [IP: 185.125.190.36 80]
#6 2.083 Ign:14 http://ports.ubuntu.com/ubuntu-ports focal-backports/universe i386 Packages
#6 2.177 Err:15 http://ports.ubuntu.com/ubuntu-ports focal-security/restricted i386 Packages
#6 2.177   404  Not Found [IP: 185.125.190.36 80]
#6 2.180 Ign:16 http://ports.ubuntu.com/ubuntu-ports focal-security/universe i386 Packages
#6 2.180 Ign:17 http://ports.ubuntu.com/ubuntu-ports focal-security/multiverse i386 Packages
#6 2.180 Ign:18 http://ports.ubuntu.com/ubuntu-ports focal-security/main i386 Packages
#6 2.196 Reading package lists...
#6 2.624 E: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/focal/multiverse/binary-i386/Packages  404  Not Found [IP: 185.125.190.36 80]
#6 2.624 E: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/focal-updates/main/binary-i386/Packages  404  Not Found [IP: 185.125.190.36 80]
#6 2.624 E: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/focal-backports/main/binary-i386/Packages  404  Not Found [IP: 185.125.190.36 80]
#6 2.624 E: Failed to fetch http://ports.ubuntu.com/ubuntu-ports/dists/focal-security/restricted/binary-i386/Packages  404  Not Found [IP: 185.125.190.36 80]
#6 2.624 E: Some index files failed to download. They have been ignored, or old ones used instead.
------
executor failed running [/bin/sh -c dpkg --add-architecture i386 && apt update]: exit code: 100
```

Removal of this line of code results in everything building correctly and with the tests passing. I am building on an x64 host:
```
$docker run openspiel dpkg --print-architecture
arm64
```

So if this change is necessary for other devices (which would be anti-thetical to Docker), then another solution would be necessary. I'm not an expert in Docker by any means though.

### CODE REVIEW

**Comment by MaxOSmith** [comment]
I signed the CLA.

I also tried before arriving at this solution various cache cleaning flags at the docker and apt level.

**Comment by lanctot** [comment]
Thanks!

**Comment by MaxOSmith** [comment]
No worries!

Confirming the flag prevents building on Apple silicon, and doesn't prevent building from my `amd64` processor on my Windows tower.

**Comment by lanctot** [comment]
Ok thanks. You can leave the PR open until it gets merged (later this week) and it will be closed when I sybc our internal repos with github.

**Pull request merged**
