### PR TITLE
Add get_all_histories

### PR DESCRIPTION
**Pull request by jhtschultz**
Addresses Issue #401. As requested, `GetAllHistories()` returns a `std::vector<std::unique_ptr<State>>`.

> Use State::FullHistory to check for equality, rather than State::ToString

Is there any reason we need to actually perform this check for equality or will a DFS suffice? I couldn’t come up with a scenario in which there’s a difference so I implemented it as a straightforward DFS. Wanted to check though because there’s been some discussion around this issue and I could well have missed something.

I gave `GetAllHistories()` its own file. Seemed like the right way to go but if there’s a preference for including it in the `get_all_states` file as a separate function I’m happy to do that.

And if there’s anything else I can do for this PR just let me know :)

### CODE REVIEW

**Comment by gabrfarina** [comment]
I'm not a maintainer, but I think there was [consensus](https://github.com/deepmind/open_spiel/issues/401#issuecomment-706400869) that the code that counts infosets in `open_spiel/examples/count_all_states.cc` would need to move to GetAllHistories instead to avoid undercounting in some classes of games (#399).

Thanks for this, once it lands I will move the tests in #376 to use it :-)

**Comment by jhtschultz** [comment]
That ought to do it. Thanks @gabrfarina!

**Comment by lanctot** [comment]
Oh hey John, seems like there is a conflict with master, can you double check that your last commit was included in the update? (I may have done the update before your last commit.)

**Comment by lanctot** [comment]
Just checked, it was not included. Sorry, completely missed that (I modified the same file internally.)

But also: I don't think we want to replace states entirely with histories in that example because it will double count states in the perfect information, right?

I thought the plan would be to use histories to count info states? Or we can just use this example for imperfect info games (in which case let's add a check).

**Pull request closed without merging**
