### PR TITLE
Tabular Policy pickling fix

### PR DESCRIPTION
**Pull request by aliyakamercan**
PR for tabular policy python pickling issue mentioned in #234

### CODE REVIEW

**Comment by aliyakamercan** [comment]
@googlebot I fixed it.

**Comment by lanctot** [comment]
Cool thanks. But are we sure the game object is gusranteed to get deserialized before the game type?

**Comment by ayakamercan-coatue** [comment]
It is, but if you want to make `GameType` serializable anyways, let's not merge this. I will work on adding serialization to `GameType`.

**Comment by aliyakamercan** [comment]
It is, but if you want to make GameType serializable anyways, let's not merge this. I will work on adding serialization to GameType.

**Pull request closed without merging**
