### PR TITLE
Specify a number of turns to play in Goofspiel.

### PR DESCRIPTION
**Pull request by michalsustr**
This change allows to play Goofspiel with a full deck of cards, but with a limited number of turns.

### CODE REVIEW

**Comment by lanctot** [comment]
Hi @michalsustr, I have a fix to Goofspiel coming that will require a merge with this PR. In short, to get the MDP best response working on simultaneous move games, the observations need to be Markovian. 

Currently they are not because a player does not have any way of knowing which point cards were remaining. I will point you to the commit when it goes live. Note: this will be a backward-incompatible change to Goofspiel; let me know if that creates any issues for you.

**Comment by lanctot** [comment]
Hi @michalsustr the commit I mentioned is here, if you're curious: https://github.com/deepmind/open_spiel/commit/898ea51ae6ce4f34c788007ba710cf3ced127ca4

**Comment by michalsustr** [comment]
Just merged, hopefully everything is ok. I was getting a number of unrelated test errors on my local machine though, but didn't have time to investigate what is the problem (something about serialization, maybe my pybind needs upgrade again?)

```Traceback (most recent call last):
  File "/home/michal/.python_envs/os/lib/python3.8/site-packages/absl/testing/parameterized.py", line 284, in bound_param_test
    return test_method(self, *testcase_params)
  File "/home/michal/Code/open_spiel/build_git/50bef27f/open_spiel/python/tests/games_sim_test.py", line 226, in test_multiplayer_game
    self.sim_game(game)
  File "/home/michal/Code/open_spiel/build_git/50bef27f/open_spiel/python/tests/games_sim_test.py", line 140, in sim_game
    self.serialize_deserialize(game, state, check_pyspiel_serialization,
  File "/home/michal/Code/open_spiel/build_git/50bef27f/open_spiel/python/tests/games_sim_test.py", line 105, in serialize_deserialize
    unpickled_state = pickle.loads(pickled_state)
AttributeError: 'pyspiel.State' object has no attribute '__dict__'
```

and 

```
ERROR: test_playthrough_python_iterated_prisoners_dilemma_turn_based.txt (__main__.PlaythroughTest)
PlaythroughTest.test_playthrough_python_iterated_prisoners_dilemma_turn_based.txt
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/michal/Code/open_spiel/build_git/50bef27f/open_spiel/python/../integration_tests/playthrough_test.py", line 112, in <lambda>
    test_func = lambda self, basename=basename: self.run_test(path, basename)
  File "/home/michal/Code/open_spiel/build_git/50bef27f/open_spiel/python/../integration_tests/playthrough_test.py", line 80, in run_test
    expected, actual = generate_playthrough.replay(file_path)
  File "/home/michal/Code/open_spiel/build_git/50bef27f/open_spiel/python/algorithms/generate_playthrough.py", line 482, in replay
    return (original, playthrough(**kwargs))
  File "/home/michal/Code/open_spiel/build_git/50bef27f/open_spiel/python/algorithms/generate_playthrough.py", line 128, in playthrough
    lines = playthrough_lines(game_string, alsologtostdout, action_sequence,
  File "/home/michal/Code/open_spiel/build_git/50bef27f/open_spiel/python/algorithms/generate_playthrough.py", line 316, in playthrough_lines
    state = game.new_initial_states()[-1]
RuntimeError: Tried to call pure virtual function "Game::new_initial_state"
```

**Comment by lanctot** [comment]
You need to update your pybind11. We made a change that requires a refresh of your cloned repos. Should be as easy as running `git pull` in the top-level pybind11 dir.

**Pull request merged**
