### PR TITLE
fix SampleCards bug in universal_poker/card_set.

### PR DESCRIPTION
**Pull request by Liuweiming**
Same as #181. 
added some comments to the function `CardSet::SampleCards`.

### CODE REVIEW

**Comment by lanctot** [comment]
> It seems impossible since I accidentally deleted the repository of PR(#181). Sad.

Oh no! :( Yeah it seems that the commits are now pointing to an unknown repository.

Well if you find a way to get it back or feel motivated enough to redo it, it's still a very welcome fix.

**Comment by Liuweiming** [comment]
The fix is included in this PR. So to me, it is OK to merge this PR and close PR(#181).

**Comment by lanctot** [comment]
Oh really? The fix is only 3 lines in card_set.cc in this commit: https://github.com/deepmind/open_spiel/pull/183/commits/c89bc02df17c8435c34e580a82fb7768ec11ea4b  ?

**Comment by Liuweiming** [comment]
Yes. It is a single character fix : )

**Comment by lanctot** [comment]
Haha, the best kind! Ok I will import this and it will be merged in next Monday's update after review. (Please leave it open). Thanks!

**Comment by lanctot** [comment]
Hi @Liuweiming, I had an issue importing this. I think it's on our end because we have been making a lot of changes that affect the workflow between our internal repos and github. 

Could you pull from master and push any merge commits ?

Sorry for the trouble!

**Comment by lanctot** [comment]
It's been fixed and imported, thanks @jblespiau and @tewalds !

Will get merged in the next Monday update, thanks!

**Comment by dennisjay** [comment]
OK did have a look at the pull request and this is perfectly fine. Didn't expect a error there but in latter versions this function was not used. 

@lanctot thanks for your message at linkedin it did receive it

**Pull request merged**
