### PR TITLE
catan-support

### PR DESCRIPTION
**Pull request by Inujal**
Pull request for deepmind/open_spiel#192 .
I omitted the CATAN implementation since it is not clear if I am allowed to upload it. These files are able to handle all features of the CATAN base game with my implementation, except players trading with each other. I am looking forward to suggestions and corrections.

### CODE REVIEW

**Comment by lanctot** [comment]
Sorry, I don't understand. If the Catan implementation is missing, what do these files do? They don't compile, I guess? And what do you want us to look at?

It is ok for you to submit the files for a PR. It's now on our side to check into whether we can merge them. We might have to get permissions. I will look into this and get back to you.

**Comment by Inujal** [comment]
Oh ok, then I misunderstood you. I thought you maybe could look if you see any errors on this side of the implementation. The Catan implementation is not very presentable yet, I still have to do a lot of refactoring. Also, I have to check if I am allowed to share the implementation before finishing the thesis. I also do not want to make the implementation public without the consent of the publisher.

**Comment by lanctot** [comment]
> Oh ok, then I misunderstood you. I thought you maybe could look if you see any errors on this side of the implementation. The Catan implementation is not very presentable yet, I still have to do a lot of refactoring. 

Ahh no problem, we can still do that, sure! But how is it even compiling without having the Catan code underneath? I guess I need to look at the code. :)

> Also, I have to check if I am allowed to share the implementation before finishing the thesis. I also do not want to make the implementation public without the consent of the publisher.

Makes perfect sense. I have contacted our legal team and we'll check this out from our side, and will be in touch. I suggest you talk to your supervisor... do you know if you would also need permissions from your University?

**Comment by Inujal** [comment]
> Ahh no problem, we can still do that, sure! But how is it even compiling without having the Catan code underneath? I guess I need to look at the code. :)

Yes, you would have to look at the code.

> Makes perfect sense. I have contacted our legal team and we'll check this out from our side, and will be in touch. I suggest you talk to your supervisor... do you know if you would also need permissions from your University?

I talked to my supervisor and he is fine with me uploading it. He also pointed out, that I should use the correct license (for example cc). Other than that, does the University not seem to be involved.

**Comment by lanctot** [comment]
Discussed this with the author, closing for now until further notice.

**Pull request closed without merging**
