### PR TITLE
Stones and Gems new game

### PR DESCRIPTION
**Pull request by tuero**
Lite version of Boulder Dash/Emerald Mines type game.

### CODE REVIEW

**Comment by tuero** [comment]
@googlebot I signed it!

**Comment by tuero** [comment]
@lanctot Final changes are in (updated observation tensor, renaming to generic game along with elements/references)!

**Comment by elkhrt** [comment]
Thanks for the contribution!
Could you run clang-format on the code, and amend the playthrough to be a smaller instance of the game (less than 1Mb would be ideal).
Also, is the game you've implemented a standard one? Any references?

**Comment by tuero** [comment]
Hi Edward!

I've ran clang-format on the code and reduced the playthrough to ~270kb. There aren't really any papers on this type of environment in terms of references, so I've made a comment at the top of the header which cites the 2 commercial games this environment is based off of.

**Pull request merged**
