### PR TITLE
Resume training from most-recent checkpoint in Libtorch AlphaZero

### LINKED ISSUE #571: Libtorch AlphaZero: Resume training from most recent checkpoint
This feature was talked about before with @selfsim and @SwiftGodDev.

I have been working on it a little bit and should hopefully have something soon, but I just thought I would make an issue to ensure that it is not forgotten about.

### PR DESCRIPTION
**Pull request by christianjans**
Will close #571.

Remaining tasks:
- [x] Address TODO comments.
- [x] Update LibTorch AZ's README with complete running instructions (i.e. include libnop dependency).

### CODE REVIEW

**Comment by lanctot** [comment]
Thanks @christianjans!

**Comment by christianjans** [comment]
My pleasure @lanctot! There are still a few things left to add, I will continue to chip away at the TODOs.

Also, I recall we talked before about how the replay buffer (in addition to the NN and NN optimizer) should be saved in order to properly restart training. I was curious, does OpenSpiel have any dependencies that support the serialization of C++ objects?

**Comment by lanctot** [comment]
We do do custom serialization, but each game and state can be serialized quite easily as text. Could be neat to look into a more efficient binary version of those that could potentially zipped.

You could just use an optional dep since Libtorch is already optional, but why not just do it in house? What format does the replay buffer have now? Isn't it just records of games and the outcomes of searches and games, or is there more to save? 

Do you know of any general projects to do this? In your csse the dependency would be entirely optional so it would not add any additonal maintenance burdens. Just curious about whether it makes it easier.

**Comment by christianjans** [comment]
Sorry for the late response, but yeah, great questions.

> What format does the replay buffer have now? Isn't it just records of games and the outcomes of searches and games, or is there more to save?

Currently, from a brief search of OpenSpiel, I think just the C++ AlphaZeros and the Libtorch DQN (#575) use the [circular buffer](https://github.com/deepmind/open_spiel/blob/master/open_spiel/utils/circular_buffer.h) template class. In the AlphaZeros, the circular buffer is used to store `double` values: https://github.com/deepmind/open_spiel/blob/53eeb6127578f91e88a6c0451983d10e3509446d/open_spiel/algorithms/alpha_zero_torch/alpha_zero.cc#L204 and `TrainInputs`: https://github.com/deepmind/open_spiel/blob/53eeb6127578f91e88a6c0451983d10e3509446d/open_spiel/algorithms/alpha_zero_torch/alpha_zero.cc#L262 which are in the form of: https://github.com/deepmind/open_spiel/blob/53eeb6127578f91e88a6c0451983d10e3509446d/open_spiel/algorithms/alpha_zero_torch/vpnet.h#L90-L95 The C++ DQN stores transitions in the circular buffer: https://github.com/Asugawara/open_spiel/blob/9e1d2e45ac158e3287e7fd01bb88126fa8cef9e4/open_spiel/algorithms/dqn_torch/dqn.h#L86 which are of the form: https://github.com/Asugawara/open_spiel/blob/9e1d2e45ac158e3287e7fd01bb88126fa8cef9e4/open_spiel/algorithms/dqn_torch/dqn.h#L37-L44.

> You could just use an optional dep since Libtorch is already optional, but why not just do it in house?

Reading and writing a circular buffer consisting of `double`s to a binary file is no problem using the C++ STL:
```c++
// In circular_buffer.h
template <class T>
class CircularBuffer {
  ...
  void Save(const std::string& path) {
    std::ofstream output_file_stream(path, std::ios::binary);
    output_file_stream.write((char*) &max_size_, sizeof(int));
    output_file_stream.write((char*) &total_added_, sizeof(int64_t));
    typename std::vector<T>::size_type data_size = data_.size();
    output_file_stream.write((char*) &data_size, sizeof(typename std::vector<T>::size_type));
    output_file_stream.write((char*) data_.data(), data_.size() * sizeof(T));
    output_file_stream.close();
  }
  void Load(const std::string& path) {
    std::ifstream input_file_stream(path, std::ios::binary);
    input_file_stream.read((char*) &max_size_, sizeof(int));
    input_file_stream.read((char*) &total_added_, sizeof(int64_t));
    typename std::vector<T>::size_type data_size = 0;
    input_file_stream.read((char*) &data_size, sizeof(typename std::vector<T>::size_type));
    data_.resize(data_size);
    input_file_stream.read((char*) &data_[0], data_.size() * sizeof(T));
    input_file_stream.close();
  }
  ...
}

// Saving and loading a CircularBuffer:
CircularBuffer<double> my_buffer(/*max_size=*/4);
my_buffer.Add(3.14);
my_buffer.Add(10.0);
my_buffer.Save("my_buffer.data");
my_buffer.Load("my_buffer.data");
```
However, I have run into issues when attempting to read/write a circular buffer containing non-"plain-old data" (types which dynamically allocate memory, such as `std::vector`) to a binary file. For example, saving and loading a circular buffer consisting of `TrainInputs` cannot be done due to the `TrainInputs` struct containing `std::vector`s and an `std::map` (`ActionsAndProbs`).

I am definitely no C++ expert, so I may be missing a solution to this. However, this is just the information I could find around the internet surrounding this problem of serializing non-"plain-old data".

> Do you know of any general projects to do this?

I was looking around for projects that could serialize objects such as this, and although I haven't tried it yet, perhaps [libnop](https://github.com/google/libnop) would work? It's from Google and seems to do what we need.

**Comment by christianjans** [comment]
Hi @lanctot,

This should be good to review now. I went with the libnop optional dependency route and it's working great!

Just as an aside, and maybe for those who are interested in using this feature of LibTorch AlphaZero, here are some brief experiments to show the learning progress on Tic Tac Toe when training is paused and then resumed. The experiments all used the same hyperparameters:
```bash
./build/examples/alpha_zero_torch_example --nn_width=64 --nn_depth=2 --game=tic_tac_toe --replay_buffer_size=16384 --replay_buffer_reuse=4 --checkpoint_freq=25 --max_simulations=50 --actors=2 --evaluators=1
```

This first graph is the "baseline" experiment, it is run for 50 steps without interruption:


This second graph shows an experiment that was first run for 25 steps and then stopped. Then, training was resumed for another 25 steps for a total of 50 steps:


This third graph shows an experiment that was first run for 10 steps and then stopped. Then, training was resumed for another 10 steps and then stopped again. This was done until the experiment reached 50 total steps:


From the graphs, it is apparent that there are some differences when training is restarted, but I think the changes in this PR mitigate these differences pretty well. Additionally, and maybe more importantly, the networks are still learning after resuming training, and the AlphaZero experiments that undergo starts and stops in their training reach similar performance against MCTS players as the baseline AlphaZero experiment.

**Comment by SwiftGodDev** [comment]
Hi @christianjans I tried building openspiel with LIBNOP and LIBTORCH but it gives this error:

/open_spiel/open_spiel/examples/alpha_zero_torch_example.cc:113:12: error: no member named 'FromFile' in
      'open_spiel::algorithms::torch_az::AlphaZeroConfig'
    config.FromFile(positional_args[1]);
    ~~~~~~ ^

**Comment by christianjans** [comment]
Hi @SwiftGodDev, sorry about that! Thanks for catching it, I realized I had some uncommitted changes. It should be working now.

**Comment by lanctot** [comment]
@christianjans this is great progress, thanks!

I was not able to take a look today so I'll do a deeper dive next week.

**Comment by SwiftGodDev** [comment]
Hi @christianjans I have run into a **Segmentation fault (core dumped)** error after I resumed training.

**Comment by christianjans** [comment]
No worries, @lanctot.

Hi @SwiftGodDev, thanks for the comment. Could you provide some more information? What system (OS, hardware, LibTorch version, etc.) are you using? What commands did you run to install and start LibTorch AlphaZero? I just tried a fresh install of this branch on MacOS and it is working fine:
```bash
~ $ mkdir open_spiel_test
open_spiel_test $ cd open_spiel_test/
open_spiel_test $ git clone https://github.com/christianjans/open_spiel.git
open_spiel_test $ cd open_spiel/
open_spiel $ git checkout -b resume_training origin/alpha_zero_torch_resume_training
open_spiel $ nano open_spiel/scripts/global_variables.sh  # I turned on libnop and LibTorch, and used the MacOS version of LibTorch.
open_spiel $ ./install.sh
... output from installing ...
open_spiel $ ./open_spiel/scripts/build_and_run_tests.sh --build_only=true
...  output from building ...
open_spiel $ ./build/utils/circular_buffer_test
... output (or no output) from the test ...
open_spiel $ ./build/utils/serializable_circular_buffer_test
... output (or no output) from the test ...
open_spiel $ ./build/libnop/libnop_integration_test
... output (or no output) from the test ...
open_spiel $ ./build/algorithms/alpha_zero_torch/torch_model_test
... output (or no output) from the test ...
open_spiel $ ./build/libnop/libnop_integration_test
... output (or no output) from the test ...
open_spiel $ ./build/algorithms/alpha_zero_torch/torch_model_test
... output (or no output) from the test ...
open_spiel $ ./build/algorithms/alpha_zero_torch/torch_vpnet_test
... output (or no output) from the test ...
open_spiel $ ./build/libtorch/torch_integration_test
... output (or no output) from the test ...
open_spiel $ ./build/examples/alpha_zero_torch_example --nn_width=64 --nn_depth=2 --game=tic_tac_toe --replay_buffer_size=16384 --replay_buffer_reuse=4 --checkpoint_freq=25 --max_simulations=50 --actors=2 --evaluators=1 --path=az_ttt_resume_working_test  # I let this run for about 2 minutes.
Logging directory: az_ttt_resume_working_test
Creating model: az_ttt_resume_working_test/vpnet.pb
Playing game: tic_tac_toe
Loading model from step 0
^CJoining all the threads.
Exiting cleanly.
open_spiel $ ./build/examples/alpha_zero_torch_example az_ttt_resume_working_test/config.json  # I let this run for about 2 minutes.
Logging directory: az_ttt_resume_working_test
Using existing model: az_ttt_resume_working_test/vpnet.pb
Playing game: tic_tac_toe
Loading model from step -1
^CJoining all the threads.
Exiting cleanly.
open_spiel $ ./build/examples/alpha_zero_torch_example az_ttt_resume_working_test/config.json  # I let this run for about 2 minutes.
Logging directory: az_ttt_resume_working_test
Using existing model: az_ttt_resume_working_test/vpnet.pb
Playing game: tic_tac_toe
Loading model from step -1
^CJoining all the threads.
Exiting cleanly.
```

**Comment by SwiftGodDev** [comment]
Hi @christianjans sorry for the late reply. I am no longer getting the error.

**Pull request merged**
