### PR TITLE
Infer tensor shapes automatically from game's Observer.

### PR DESCRIPTION
**Pull request by michalsustr**

### CODE REVIEW

**Comment by elkhrt** [comment]
I don't think this is an improvement - it makes KuhnPoker less comprehensible; this is an important entry point for new users and it should be as easy as possible to understand.

Another (fixable) issue is that it moves a class into the external API without adequate documentation.

**Comment by michalsustr** [comment]
Will it be OK if I revert Kuhn changes and add documentation?

**Comment by elkhrt** [comment]
Actually, I don't see why TrackingVectorAllocator has to move into the
public API at all.

**Comment by michalsustr** [comment]
Not in here, true.

**Comment by michalsustr** [comment]
I will do it in a different PR: #358

**Pull request closed without merging**
