### PR TITLE
Add registration of SpielException so it can be caught in Python with…

### PR DESCRIPTION
**Pull request by michalsustr**
… more specificity than just some RuntimeError.

### CODE REVIEW

**Comment by elkhrt** [comment]
Thanks. I'm merging this and fixing the various tests you missed in the process (so there's no need for you to fix this PR).

**Comment by michalsustr** [comment]
Oh, I didn't notice the comment! Ha, well, I just pushed the changes as well. I tried to make SpielError to inherit from RuntimeError, but I didn't find an easy way to do so with pybind11 -- maybe the first thing I couldn't find in otherwise this awesome library :)

**Comment by michalsustr** [comment]
Ok, turns out the feature was not documented, but it is easy to do so!

**Comment by lanctot** [comment]
I think this was merged but did not get auto-closed because there were extra commits. @michalsustr can you check to see if everything you want is now in master?

**Comment by michalsustr** [comment]
No commits were merged. Can you import it again with the new changes? Thank you!

**Pull request merged**
