### PR TITLE
Game of Amazons

### PR DESCRIPTION
**Pull request by selfsim**
Hi @lanctot, @bartdevylder, here is the new PR with my game of amazons game implementaion.
I've generated a playthrough. Let me know if there is anything outstanding.
-selfsim

### CODE REVIEW

**Comment by selfsim** [comment]
@googlebot I fixed it.

**Comment by selfsim** [comment]
@googlebot I fixed it.

**Comment by selfsim** [comment]
@googlebot I fixed it.

**Comment by selfsim** [comment]
@googlebot I fixed it.

**Comment by lanctot** [comment]
Thanks @selfsim. Two tests are failing: amazon_test, and playthrough_test. Can you take a look locally to see what's going on? Thanks!

**Comment by selfsim** [comment]
@lanctot , working on it, will let you know when they are fixed.

**Comment by lanctot** [comment]
The merge from master got messed up, can you copy the files and submit a new PR?

**Pull request closed without merging**
