### PR TITLE
change rbc sense to behave like APL's sense rules

### PR DESCRIPTION
**Pull request by acxz**
Address 1) of #811 

@michalsustr

### CODE REVIEW

**Comment by lanctot** [comment]
Hi @acxz,

Thanks for the PR. There were compilation errors when trying to run the test. Can you take a look?

**Comment by acxz** [comment]
I'm afraid I do not know why the test is failing, @michalsustr when you get the chance would appreciate you taking a look.

**Comment by lanctot** [comment]
@acxz just checking in to see if you plan to continue working on this? If so, could I ask you to pull from master and push the merge commit to retrigger an invocation of the tests? The old one from April has been deleted.

**Comment by acxz** [comment]
Sure thing

**Comment by lanctot** [comment]
Closing for now, please feel free to re-open if you continue working on this.

**Pull request closed without merging**
