### PR TITLE
add a "human bot"

### PR DESCRIPTION
**Pull request by juliendehos**
Thanks for sharing this project.
This PR adds a bot and an example, in the python interface, which lets a human play against a bot.

### CODE REVIEW

**Comment by lanctot** [comment]
Thank you for your contribution! We are still figuring out the tools and workflow for how to properly integrate code from github pull requests. Once we do, we will come back to take a look at merging this pull request. Expect this to be at lease one week, possibly several. Apologies for the delay.

**Comment by juliendehos** [comment]
Ok, thanks.

**Comment by locked-deepmind** [comment]
Thanks for this; we're almost there on the process for integrating github PRs. In the meantime, could you sign the CLA (above)?

**Comment by OpenSpiel** [comment]
We can now merge PR :)

Feel free to sign the CLA if you want this to be included!

**Comment by juliendehos** [comment]
Ok, thanks. I'm trying to sign the CLA from this page https://cla.developers.google.com/about/google-corporate but I have to log in to a google account and I don't have one. How can I sign the CLA without a google account ?

**Comment by OpenSpiel** [comment]
That's a good question, but unfortunately I do not know if it is possible.

I know you can get a google account without having a Gmail address (it binds any mail address to a Google account: https://www.wikihow.com/Make-a-Google-Account-Without-Gmail). You can also create a google account. I tried the link without being logged, and I think it is likely that you require a google account.

**Comment by juliendehos** [comment]
It seems to work. Thank you very much.

**Comment by juliendehos** [comment]
@googlebot I signed it!

**Pull request merged**
