### PR TITLE
Update install.md

### PR DESCRIPTION
**Pull request by rahulsavani**
missing "." for current directory for docker option 3 build command

### CODE REVIEW

**Comment by lanctot** [comment]
Thanks for catching @rahulsavani !

Can you sign the CLA?

**Comment by rahulsavani** [comment]
> Thanks for catching @rahulsavani !
> 
> Can you sign the CLA?

Signed earlier today, but maybe waiting in a queue of some sort?

**Comment by lanctot** [comment]
Hi @rahulsavani, I think maybe you didn't do this step:

> Once you've signed (or fixed any issues), please reply here with @googlebot I signed it! and we'll verify it.

**Comment by lanctot** [comment]
Uhh.. oddly now it's showing as ok. My last email quoting that string may have triggered it :)

**Comment by rahulsavani** [comment]
> Uhh.. oddly now it's showing as ok. My last response quoting that string may have triggered it :)

Thanks, my bad, totally missed that.

**Pull request merged**
