### PR TITLE
Remove necessity to keep explicit default policy for MCCFR solvers

### PR DESCRIPTION
**Pull request by inejc**
These changes are based on discussions in https://github.com/deepmind/open_spiel/issues/149. The idea is to remove the need to keep an explicit default policy within MCCFR solvers and thus make them feasible to run on large games where memory constraints are tighter.

The proposed changes allow for usage of:
- `TabularPolicy` which is the default behavior and the current state
- `UniformPolicy` for cases where the inferred average CFR policy will only ever be queried with a `State` instance
- `nullptr` which will enable to also query the inferred policy with an `info state string` but move the handling of info state lookup fails to the external caller (empty policy would be returned in that case)

### CODE REVIEW

**Comment by inejc** [comment]
@googlebot I signed it!

**Comment by lanctot** [comment]
This is great, thanks! 

I'm making a few (mostly) cosmetic changes. Turns out we don't have to store a tabular policy after all (we have a UniformPolicy object and the best response code does state-based queries already.

Should get merged in Monday's update. (Please don't close the PR.)

**Comment by lanctot** [comment]
Nevermind, I spoke too soon. They do indeed need to be tabular policies due to assumptions in the best response code (which we should probably tweak eventually...)

**Comment by inejc** [comment]
> Nevermind, I spoke too soon. They do indeed need to be tabular policies due to assumptions in the best response code (which we should probably tweak eventually...)

I see... I suppose this isn't a blocker for the proposed changes?

One minor thing: we should probably rename `uniform_policy_` in solvers to `default_policy_` since this could, in theory, be something different to uniform now. Please LMK whether I can add commits to this PR or you want to potentially change that later?

**Comment by lanctot** [comment]
> I see... I suppose this isn't a blocker for the proposed changes?

Correct! It's already under internal review, which should be easy to get done today, so will almost surely get merged in Monday's update.
 
> One minor thing: we should probably rename `uniform_policy_` in solvers to `default_policy_` since this could, in theory, be something different to uniform now. Please LMK whether I can add commits to this PR or you want to potentially change that later?

Yep, that was one of the changes I made :) (renaming to default_policy_) Please don't add commits at this point because I've already imported the PR and the changes would clash with mine.

**Pull request merged**
