### PR TITLE
add eva pytorch

### PR DESCRIPTION
**Pull request by Asugawara**
Hi! @lanctot!

It took me to implement EVA and experiments, but I added it in PyTorch!

These figures are a comparison of the Nash Conv averaged over three times of EVA agent. 

スクリーンショット 2020-12-18 23 27 27
スクリーンショット 2020-12-18 23 27 39

### CODE REVIEW

**Comment by lanctot** [comment]
Thanks @Asugawara ! Most of the team are on vacation now so we will take a look after the holidays. 

Btw curious why try it in Kuhn and Leduc? Was it because the TF tests had it running in Kuhn? This algorithm was not designed for multiagent partially observable games.

**Comment by Asugawara** [comment]
I appreciate your reply on your day off!

>Btw curious why try it in Kuhn and Leduc? Was it because the TF tests had it running in Kuhn?

Because the default argument is Kuhn in EVA's example.
https://github.com/deepmind/open_spiel/blob/master/open_spiel/python/examples/eva.py#L36

>This algorithm was not designed for multiagent partially observable games.

Oh... I understand why EVA didn't converge and was slow...
I'll try to run another game referencing the article!

Have a great vacation!

**Comment by Asugawara** [comment]
Thank you Dr. @lanctot!
And Happy New Year!
I hope to contribute more this year!

**Comment by lanctot** [comment]
> Thank you Dr. @lanctot!
> And Happy New Year!
> I hope to contribute more this year!

Happy New Year to you too! That is amazing, I look forward to that. The PRs have been great; you are laying down the foundation of our PyTorch support. Thanks for all your work. ;-)

**Pull request merged**
