### PR TITLE
Play trained Libtorch AlphaZero model

### PR DESCRIPTION
**Pull request by christianjans**
Play a trained Libtorch AlphaZero model against human, random, or MCTS bots.

This pull request implements a human bot implementation in `open_spiel/bots/` based on the human bot in `open_spiel/python/bots/`.

### CODE REVIEW

**Comment by lanctot** [comment]
Awesome, thanks @christianjans !!

**Comment by selfsim** [comment]
Confirmed working for amazons

**Comment by christianjans** [comment]
Thanks guys! There is still some clean-up that I think can be done. I will make this a draft until it is ready for review.

**Comment by lanctot** [comment]
> Thanks guys! There is still some clean-up that I think can be done. I will make this a draft until it is ready for review.

BTW just so you know: I'm waiting for you to let us know what it's ready to look at. Thanks.

**Comment by christianjans** [comment]
@lanctot, oh sorry! Yes, it should be good to review now.

**Pull request merged**
