### PR TITLE
Fix GLIBCXX_3.4.29 not found error in the Julia wrapper

### PR DESCRIPTION
**Pull request by findmyway**
It seems this version is not shipped with Julia@v1.6.1. The only way left is to make a symlink or remove libstdc++.so.6 from the prebuilt julia binary.

- [ ] Check whether making a symlink works or not.

### CODE REVIEW

**Comment by lanctot** [comment]
Can you pull changes from master and try again?

**Comment by lanctot** [comment]
Hi @findmyway,

I had to disable the julia test this morning: https://github.com/deepmind/open_spiel/commit/cb327b1d662e3552416c9e10af61cf994ae6a746

Can you add it back in this branch?

**Comment by findmyway** [comment]
Yes, sure. I'm working on it.

**Comment by lanctot** [comment]
IIRC we needed a copy command previously, see https://github.com/deepmind/open_spiel/commit/885dd00c1ac0839f641a8e9c2c68bee5e7f16f4d

**Comment by lanctot** [comment]
I've disabled the JAX NFSP test, importing this now, thanks for the fix!

**Pull request merged**
