### PR TITLE
Fix cmake equality bug

### PR DESCRIPTION
**Pull request by ssokota**
cmake EQUAL only returns true if inputs are equal and are valid numbers

### CODE REVIEW

**Comment by ssokota** [comment]
@googlebot I signed it!

**Comment by lanctot** [comment]
Thanks!

**Comment by lanctot** [comment]
Hmm, seems to be failing tests (nit compiling in abseil). Not sure why, I guess you didn't see these?

**Comment by lanctot** [comment]
Looks to me like `-O2` triggers a bug in abseil? That'd be quite a surprise to me but I have no other explanation.

**Comment by lanctot** [comment]
Confirmed: https://github.com/abseil/abseil-cpp/issues/832

We will have to increase our abseil version.

**Comment by lanctot** [comment]
@ssokota, can you change the version tag on this line: https://github.com/deepmind/open_spiel/blob/53eeb6127578f91e88a6c0451983d10e3509446d/open_spiel/scripts/install.sh#L87

from `20200923.1` to `20200923.3`? I'd like to use this PR to trigger tests to be sure everything else still works with that update.

**Comment by lanctot** [comment]
Ok looking good. Oddly thread_test now fails but only on Ubuntu 18.04.

**Comment by lanctot** [comment]
I would like to get this in ASAP. For now, can you comment out that test for now, here: https://github.com/deepmind/open_spiel/blob/53eeb6127578f91e88a6c0451983d10e3509446d/open_spiel/utils/CMakeLists.txt#L80

(and add a comment that it fails on Ubuntu 18.04 using the Testing build type). We can fix it and re-enable later.

**Comment by lanctot** [comment]
Now the Julia test fails. Any ideas, @findmyway ?

**Comment by findmyway** [comment]
That seems to be the old famous glibc mismatch error. You can disable it first. Let me test it locally and see how to fix it gracefully.

**Comment by lanctot** [comment]
I think these are unrelated to @ssokota 's change. I had to make them on master too for the sync to github today, and I haven't even imported the change yet. 

The Julia test is now failing on master too: https://github.com/deepmind/open_spiel/actions/runs/849347899

Something must have changed on the machines that runt he tests on github. I'm temporarily disabling the julia test until we can fix it.

**Pull request merged**
