### PR TITLE
Use random simulation for crowd modelling 2d test

### PR DESCRIPTION
**Pull request by TheoCabannes**
This PR is failing due to an issue on crowd modelling 2d implementation. I do not know what the issue is but I am creating it in order to solve it. This PR is the child of the closed PR https://github.com/deepmind/open_spiel/pull/648

### CODE REVIEW

**Comment by lanctot** [comment]
Internally, I am getting the same error as you were getting with #648:

```
ChanceOutcomesTest, game = mfg_crowd_modelling_2d

RandomSimTest, game = mfg_crowd_modelling_2d, num_sims = 3
Information state vector size: 0
Observation vector size: 41
Utility range: -inf inf
Starting new game..
Initial state:
State:
initial
player -1
Spiel Fatal Error: third_party/open_spiel/tests/basic_tests.cc:104 action < expected_length
action = 10, expected_length = 10
```

**Comment by TheoCabannes** [comment]
Quoting @RaphaelMarinier comment on the previous PR #648:

> Regarding crowd_modelling_2d_test, I have a high suspicion that this is caused by a bug when computing the observation tensor. Those bugs were fixed in the 1D game [here](https://github.com/deepmind/open_spiel/commit/052d88ca99063834cf8fe70bec3a1bdaa2d5ed45), but are still present in the 2D version. I just fixed them internally.

**Comment by lanctot** [comment]
Hmm, it is failing here: https://github.com/deepmind/open_spiel/blob/c81400755106328ad25a522a9d9bc79f4e3501a7/open_spiel/tests/basic_tests.cc#L118

That means there is an action in the legal actions that is larger than MaxChanceOutcomes (if it's a chance node) or NumDistinctActions (if it's a decision node)

**Comment by TheoCabannes** [comment]
I wonder if MaxChanceOutcomes should be size*size:
https://github.com/deepmind/open_spiel/blob/c81400755106328ad25a522a9d9bc79f4e3501a7/open_spiel/games/mfg/crowd_modelling_2d.h#L170

**Comment by TheoCabannes** [comment]
@lanctot using size * size for MaxChanceOutcomes solve the issue

**Comment by lanctot** [comment]
> @lanctot using size * size for MaxChanceOutcomes solve the issue

Great! Let's confirm with @perolat that it is correct, and then I will continue with the import.

**Comment by lanctot** [comment]
Merged in https://github.com/deepmind/open_spiel/commit/769b159da3edded0558a8585f9ef8542577609bb

**Pull request closed without merging**
