### PR TITLE
Average policy in mccfr

### PR DESCRIPTION
**Pull request by colibri17**
This pull requests is related to the issue https://github.com/deepmind/open_spiel/issues/499.

I created the class `AveragePolicy` which extends the base class `Policy` and implements the method `action_probabilities`. Within the solvers, the method `average_policy` initializes each time this class. @lanctot I mirrored what is done on the C++ side and this allows to return the average policy just for already explored infostates and using the random policy in the case of not explored infostates (as @VitamintK suggested). Also, I adapted the rest of the code accordingly. 
I finally compared the outputs of the tests of this new code version with the outputs of the tests of the previous one. The results are exactly the same. I report these here for future reference:
Outcome sampling:
Kuhn2P, conv = 0.010184780058560161
Kuhn3P, conv = 0.12295759857995159
Leduc2P, conv = 2.1751618625344777
External sampling:
Kuhn2P, conv = 0.7420193061644658
Kuhn2P, conv = 0.6532886929945988
Kuhn3P, conv = 1.2682464363671362
Kuhn3P, conv = 1.7098108280062134
Leduc2P, conv = 4.887844390143719
Leduc2P, conv = 4.813241731029391

As a side note: I tried to mirror the corresponding versions on the C++, but indeed between the Python and C++ versions there are some important differences. For example, I had to duplicate the class `AveragePolicy` for outcome and external sampling monte carlo, since there is no a single place to put these in Python (that would be `cfr.h`, `cfr.cc` in C++). I guess that these differences might be because the different Python counterfactual versions were developed in different moments. In my opinion a good issue might be to refactor the Python code for completely replicating the C++ side, even if this will require some effort.

@lanctot @VitamintK hope that this is what you had in mind! Please let me know if it fine to you :)

### CODE REVIEW

**Comment by lanctot** [comment]
@colibri17, this looks great! Yes this is exactly what I was hoping for... really wonderful.

Right, I see the issue, not as easy to do here. I noticed cfr.py has some shared functions use by CFR-BR too but that doesn't seem like a good place either. 

Looks like in this case `AveragePolicy` is indeed the exact same class in both cases... how about we create a mccfr_utils.py or mccfr_helpers.py module and just put it in there, then both algorithms can just import that? There might be opportunity to move more stuff in there too but no need to do that right now.

**Comment by colibri17** [comment]
Yes I think this is a good alternative. On the C++ side, methods, classes and structs for both pure CFR (cfr and cfr-br) and MCFFR (outcome sampling cfr and external sampling cfr) algorithms are placed within `cfr.h` and `cfr.cc`. But it seems to me that both in Python and in C++ the CFR algorithms have no methods or structures in common with the MCCFR ones, so it makes sense to split unrelated methods in separated modules.
Ideally we could think to refactor the code to make a super base class which contains the common structure shared by CFR and MCCFR algorithms (at the end CFR and MCCFR are both part of counterfactual algorithms). However, this is quite a lot of work and I think we would end up with complicated code, which is against the philosophy of the library of keeping things easy. 
These are my 2 cents! :)


Back to the pull requests, yes the `AveragePolicy` is exactly the same. 
Comparing the external and outcome sampling versions, there are also other methods which are exactly the same and could be moved in the `mccfr_utils.py` (look for example at `_add_avstrat`, `_add_regrets`, `_lookup_infostate_info`). For these we could create a base class containing these methods. 
If you agree, I can move `AveragePolicy` in a new module called `mccfr_utils.py `, and then open another pull request for moving `_add_avstrat`, `_add_regrets`, `_lookup_infostate_info` in `mccfr_utils.py `. Maybe, if this is the case, this new module could be just called `mccfr.py`?

**Comment by lanctot** [comment]
Hi @colibri17 , yes that sounds perfect-- let's do that (common base class in mccfr.py to put AveragePolicy and the shared methods)!

**Comment by colibri17** [comment]
Great, I am going to do the changes! Will move the shared methods in another pull request.

You're welcome! :)

**Comment by lanctot** [comment]
Seems like our testing is broken on MacOS. Will fix it tomorrow and then import this. Thanks!

**Comment by lanctot** [comment]
> Seems like our testing is broken on MacOS. Will fix it tomorrow and then import this. Thanks!

Nevermind, seems like you got unlucky and github actions CI failed. They are running properly now.

**Pull request merged**
