### PR TITLE
Collect tensor information for an observer.

### PR DESCRIPTION
**Pull request by michalsustr**

### CODE REVIEW

**Comment by elkhrt** [comment]
I don't see the advantage over just getting an Observation for the initial state.

**Comment by michalsustr** [comment]
Yes, it is very similar. It does not hold the observation data and it only needs a const & to an observer, so you do not need to pass an owning shared_ptr that is actually used just once.

**Comment by elkhrt** [comment]
But you will always have a shared_ptr in practice. I don't think is worth the additional complexity.

**Comment by michalsustr** [comment]
> But you will always have a shared_ptr in practice. I don't think is worth the additional complexity.

Sure. I just have some other code (not published yet) that needs this information, and then shared_ptr is passed around without it needing to be so with this change. But I guess it's not too important, so I will close the PR without merging.

**Pull request closed without merging**
