### PR TITLE
chore: move all games into folders.  

### PR DESCRIPTION
**Pull request by galcohensius**
Currently, some games are inside folders while other do not.

- Most games have 3 files: X.cc X.h and X_test.cc
- Some game do not contain the X_test.cc file
- Some games have 5 files. For example: bargaining, battleship

### CODE REVIEW

**Comment by lanctot** [comment]
Hi @galcohensius, can you sign the CLA ?

**Comment by lanctot** [comment]
Either I missed it or you didn't commit changes to games/CMakeLists.txt...?

We probably want to have one per subdirectory and just include them in them all in top-level one. Is there a generic way to include all the CMakeLists in all the subdirectories in one include line?

BTW, just out of curiosity... how long did this take? O:)

**Comment by galcohensius** [comment]
I did sign the CLA from my personal mail galcohensius@gmail.com 
my problem is that I can not find how to sign a 2nd CLA from my work mail because I mistakenly made with commit with my work mail.
I tried to change the author of the commit to my personal mail but it did not work.

It took 5min, I enter kind of a "repetitive robot mode": `ctrl-F6` `ctrl-c ` `F6` `ctrl-v` 
was interesting to find folders of more than 3 files and to see what they include.

**Comment by galcohensius** [comment]
I did not commit changes to games/CMakeLists.txt since I have little idea how I should change it (I am a windows user 🤦‍♂️).

+ added subdirectories to games/CMakeLists.txt

**Comment by galcohensius** [comment]
made a new PR with a CLA approved mail.

**Pull request closed without merging**
