### PR TITLE
Add default values for GameInfo in python through the binding.

### PR DESCRIPTION
**Pull request by TheoCabannes**
This enables defining a python non constant-sum-utility games without defining utility_sum.

### CODE REVIEW

**Comment by lanctot** [comment]
Thank @TheoCabannes,

I am trying to see how this enables simultaneous move games without explicittly defining player_sum? Are you working on one? If so, would great to have an example in the repos alongside the others, would you be willing to contribute it?

Also maybe these defaults should be invalid values as defaults so that we can put asserts somewhere to ensure that the necessary ones are in the valid ranges.

Tagging @elkhrt who wrote the revamp of the python games, would like his opinion on this.

**Comment by TheoCabannes** [comment]
@lanctot my description was a little bit wrong, sorry about that. I have changed it.
This enables defining non constant-sum-utility games without defining utility_sum. In non constant-sum-utility games, utility_sum does not exists, and I think that it should have a default values.

I used the virtual functions in Game to define the default values: https://github.com/deepmind/open_spiel/blob/53eeb6127578f91e88a6c0451983d10e3509446d/open_spiel/spiel.h#L742

Screen Shot 2021-05-10 at 11 03 35 AM
Screen Shot 2021-05-10 at 11 03 44 AM

**Comment by TheoCabannes** [comment]
I am working on one simultaneous game without fix utility_sum. I am happy to contribute when my implementation of the game is ready.

**Review by elkhrt — COMMENTED** [review]
I'm fine with defaulting utility_sum to zero, but please remove the other defaults.

**Comment by TheoCabannes** [comment]
I added a commit to only change utility_sum default value

**Comment by lanctot** [comment]
> I added a commit to only change utility_sum default value

Thanks. Importing this now.

**Pull request merged**
