### PR TITLE
Add import numpy as np in concept.md

### PR DESCRIPTION
**Pull request by srijanreddy98**
In line 87 of concepts.md np is used but not imported. This just adds that import statement.
```
action = np.random.choice(action_list, p=prob_list)
```

### CODE REVIEW

**Comment by lanctot** [comment]
Good catch!

**Comment by lanctot** [comment]
We have integrated this PR internally, so this will go out on the next push to github. Thanks!

**Comment by srijanreddy98** [comment]
Happy to help.

**Comment by lanctot** [comment]
Oh there was need to close it. Our push to github does that and associates the commits with it, so I like to keep it up until we do the push.

**Pull request merged**
