### PR TITLE
promote pawn to queen if pawn can promote

### PR DESCRIPTION
**Pull request by acxz**
stay consistant with APL's rbc

Address 5) of https://github.com/deepmind/open_spiel/issues/811

### CODE REVIEW

**Comment by acxz** [comment]
@lanctot I feel that the ci failures are unrelated. Can you confirm?

**Comment by lanctot** [comment]
Yeah seems like our chex version is causing issues. There may have been a recent backport or change in an unpinned dependency causing issues.

I am on vacation at the moment, so will look into it more deeply next week. I will probably include the change with the rest of the dep version changes in #807

**Comment by acxz** [comment]
thx for the quick glance, plz enjoy ur vacation, this work is not a high priority at the moment

**Comment by lanctot** [comment]
Tried a quick hack in #819 but no dice, will likely have to wait for all the other version upgrades. Sorry about that!

**Comment by lanctot** [comment]
Hi @acxz, the CI tests are now fixed on the master branch. Can you pull changes and push the merge to trigger a new invocation of the tests? Thanks!

**Pull request merged**
