### PR TITLE
Add DarkChess

### PR DESCRIPTION
**Pull request by michalsustr**
This is extension of #421 (that PR can be closed by this PR) -- I updated the code a bit and tested it. Now it is ready to be merged. The playthroughs are rather large, the dark_chess.txt is 2.6MB as there is a number of observation tensors that get printed out and the information state is stored as string concatenation of AOH. If you consider this a problem, maybe compression would be useful: a 7zip file is 18KB.

There is also a vizualization of the game playthrough in SpielViz:

image

### CODE REVIEW

**Comment by vofak** [comment]
@googlebot I consent.

**Comment by lanctot** [comment]
Hi guys, great! How is it related to https://github.com/deepmind/open_spiel/pull/421? Should we close 421?

**Comment by michalsustr** [comment]
Yes you can close #421

**Comment by BedirT** [comment]
The viz is amazing @michalsustr I didn't really know there was a GUI implementation on open_spiel. This could help a lot in my research actually. Could you guys direct me to where to check for implementing the GUI? @lanctot for the dark_hex I would love if we had the visuals (Ryan would more than me tbh :) )

**Comment by michalsustr** [comment]
@BedirT Check out [SpielViz](github.com/michalsustr/spielviz), I'm happy to take in pull requests. It uses PyGTK. I think the easiest way is to make code that builds an SVG picture that is embedded in state view (like for Chess). This is also relatively portable, if you decide for example to make a web GUI with Javascript. Hit me up on e-mail or maybe even better open an issue on the repo, I'm happy to help.

**Comment by michalsustr** [comment]
@vofak FYI DarkChess is merged.

**Comment by brianhzhang** [comment]
Currently in the dark chess implementation, it seems to me that the 50-move counter and repetition counter are public information. In particular, this means that it is always common knowledge when a pawn move is made (but of course which pawn move is not public). Is this intentional? It reduces dramatically the amount of information that is private...

**Pull request merged**
