### PR TITLE
Remove tic_tac_toe dependency from minimax algorithm

### PR DESCRIPTION
**Pull request by phcerdan**

### CODE REVIEW

**Comment by lanctot** [comment]
Nice catch, thanks!

**Comment by lanctot** [comment]
Oh right our CI tests are currently broken, should be fixed by the sync tomorrow. Will post when ready.

**Comment by lanctot** [comment]
Hi @phcerdan, the CI tests are now fixed on the master branch. Can you pull changes and push the merge to trigger a new invocation of the tests? Thanks!

**Comment by phcerdan** [comment]
@lanctot done

**Pull request merged**
