### PR TITLE
Phantom go

### PR DESCRIPTION
**Pull request by Syor**

### CODE REVIEW

**Comment by lanctot** [comment]
Thanks! There's a conflict in pyspiel_test.py, can you resolve it?

**Review by lanctot — CHANGES_REQUESTED** [review]
Can you add the game and its description to the games page? (docs/games.md)

**Comment by lanctot** [comment]
(You can ignore the failing wheels tests, they will be fixed once https://github.com/deepmind/open_spiel/pull/873 is merged on Monday.. but you will have to rerun `./install.sh` locally)

**Comment by Syor** [comment]
> Can you add the game and its description to the games page? (docs/games.md)

Sorry for the delay. I am not sure what is the proper way to edit it.

**Comment by lanctot** [comment]
> @lanctot > Can you add the game and its description to the games page? (docs/games.md)
> 
> Sorry for the delay. I am not sure what is the proper way to edit it, is there some editor?

It is plain text file. But don't worry about it, I can do it on my end.

**Review by lanctot — APPROVED** [review]

**Comment by lanctot** [comment]
Hi @Syor , the test is failing because it appears there is some Linux-specific code (specifically, the header `<asm-generic/ioctls.h>`. Can you modify the test so that it can run on MacOS?

**Pull request merged**
