### PR TITLE
[DRAFT] Adding deep best response computation with a BR value function parameter

### PR DESCRIPTION
**Pull request by ajain-23**
This PR adds functionality for computing the best response value with RL methods (e.g.  DQN, as opposed to standard exact BR) in the MFG Fictitious Play algorithm. It is a first pass towards Deep Fictitious Play for mean-field games.

### CODE REVIEW

**Comment by lanctot** [comment]
Hi @ajain-23, 

Can I ask you to pull changes from master so that we can rerun the CI tests, which broke last week? (Specifically: you just need the changes in this commit, so you can also modify it in your branch if you prefer.)

**Comment by ajain-23** [comment]
> Hi @ajain-23,
> 
> Can I ask you to pull changes from master so that we can rerun the CI tests, which broke last week? (Specifically: you just need the changes in this commit, so you can also modify it in your branch if you prefer.)

Done!

**Comment by lanctot** [comment]
Hi, just curious: does #735 and #736 replace this PR? If so, shall we close this one? 

If not, no worries! Just keep me posted on when it's ready for review or to import.

**Comment by ajain-23** [comment]
> Hi, just curious: does #735 and #736 replace this PR? If so, shall we close this one?
> 
> If not, no worries! Just keep me posted on when it's ready for review or to import.

This PR is independent of those. I will update it to incorporate the changes from 5b149b2!

**Comment by lanctot** [comment]
Ok great, thanks.

**Pull request closed without merging**
